<a href="https://colab.research.google.com/github/frankgama/CS111-Intro-to-Scientific-Computing/blob/main/Homework2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Homework 2 COMPSCI 111 UCSB Summer 2025, Frank Gama
#I confirm that I did not use ChatGPT
#or codes from the web or from past years’ assignments and that the work
#I submit is my own and my own only.

#I have been using Google colab since this is the easiest for me at the moment

import os
import time
import math
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import linalg as spla
import scipy.sparse
import scipy.sparse.linalg
from scipy import integrate
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d
%matplotlib inline
np.set_printoptions(precision = 4)

#I have to connect my colab to my drive every time I make a project
from google.colab import drive
drive.mount('/content/drive/')

# Now that I am connected, I need to be able to access the CS111 File and its
# contents
import os, sys, pathlib
PKG_NAME = "CS111"
PKG_DIR = f"/content/drive/MyDrive/{PKG_NAME}"
PARENT = os.path.dirname(PKG_DIR)




#this makes sure I connected correctly and that my kernel has access to my files
if PARENT not in sys.path:
    sys.path.insert(0, PARENT)

import cs111.LU as LU


#This homework deals with inverse matrices and permutations

#the first function will take a matrix, A and compute it's inverse (if it exists)






Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [9]:
def computeInverse(A):
  #A an nxn matrix
  #we know that PA = PLU
  #to find the inverse, we will do so indirectly by doing a couple of transformations
  # where Ly = b[P]. This meas the lower triangular times some vector y, will
  #give us a vector b, but with the applied permutation.
  #the permutaion will ensure that we can perform the LU factorization and also
  #give us a diagonalized matrix.
  #we then know that Ux = y, where x is a column vector of the inverse matrix
  #we then solve for x, add it to a dummy matrix, and repeat until we have
  #the inverse matrix.
  #it is possible that P is simply the identity matrix, but either way,
  #we need to apply it.
  L, U, P = LU.LUfactor(A)
  Ainversed = np.zeros_like(A, dtype = float)

  n = len(A)

  for i in range(n):
    #we make an array of size n with zeros
    e_j = np.zeros(n)
    #we put 1 at the ith position as we will solve for an element of I
    e_j[i] = 1
    #apply the permutation
    b = e_j[P]
    #solve for y
    y = LU.Lsolve(L,b, unit_diag = True)
    #knowing y, solve for x
    x_j = LU.Usolve(U,y)
    #add x into our dummy matrix as a vector, repeating until finished
    Ainversed[:, i] = x_j

  return Ainversed




In [10]:
#test code on given matrix showing matrix, inverse and checking it works
M = np.array([[1,4,5],
              [4,17,26],
              [3,18,30]
              ],dtype=float)
Mverse = computeInverse(M)
print(M)
print(Mverse)
eyedentity = M @ Mverse
print()


print(np.round(eyedentity,10))

np.linalg.inv(M)



[[ 1.  4.  5.]
 [ 4. 17. 26.]
 [ 3. 18. 30.]]
[[-2.      1.4286 -0.9048]
 [ 2.     -0.7143  0.2857]
 [-1.      0.2857 -0.0476]]

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


array([[-2.    ,  1.4286, -0.9048],
       [ 2.    , -0.7143,  0.2857],
       [-1.    ,  0.2857, -0.0476]])

In [11]:
#problem 2
#we are tasked with finding a vector v such that when applied to A, we get
#A[v,:] == A @ P
# this is trivial and we we can take the position of the 1 in the row, as the
#position the row will move to in the permutation
#so we get

v=[1,3,0,2]

#similarly, we are tasked with finding a w such that A[:,w] == P @ M
#here we look at the columns and the position of the 1 is the permutaion

#so we get

w = [2,0,3,1]


In [12]:
w = [2,0,3,1]
v=[1,3,0,2]
P = np.array([[0,1,0,0],
              [0,0,0,1],
              [1,0,0,0],
              [0,0,1,0]])
#random 4x4 generator
A = np.arange(16).reshape(4,4)

print(A[v,:] == P @ A)
print(A[:,w]== A @ P)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
